### ISSUE TITLE
Doesn't compile on Rust 1.47

### ISSUE THREAD

**Issue by ubolonton** [ubolonton/emacs-tree-sitter#62]
On Rust 1.47, compilation fails with a lot of errors similar to this:

```
error[E0423]: expected value, found macro `env`
   --> core/src/lang.rs:182:52
    |
182 |     "lang-node-type-named-p" fn node_kind_is_named(type_id: u16) -> bool
    |                                                    ^^^^^^^ not a value
    |
help: use `!` to invoke the macro
    |
182 |     "lang-node-type-named-p" fn node_kind_is_named(type_id!: u16) -> bool
    |                                                           ^
help: consider importing this function instead
    |
1   | use crate::lang::os::unix::process::sys::os::env;
    |

```
